### ISSUE TITLE
When you include font awesome and bootstrap it stops working

### ISSUE THREAD

**Issue by petedmarsh** [bladeSk/internet-explorer-opacity-polyfill#1]
If you include font awesome and bootstrap, like so:

``` html
<head>
...
<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
...
</head>
```

it stops working. I've tested this in a VM with IE8 on XP.

Edit: Helpful screenshots.

I'm running the demo file included with the repo.

Unmodified, I get this:

![image](https://f.cloud.github.com/assets/1192314/937270/010f3258-00d5-11e3-8e87-c4d07ca418e4.png)

With bootstrap/font awesome, I get this:

![image](https://f.cloud.github.com/assets/1192314/937264/ce94cd1a-00d4-11e3-83d5-355a539d8d14.png)

**Comment by bladeSk** [comment]
Just tested this, works fine for me in IE8 and IE7. Using fontawesome (3.2.1) + bootstrap (tested both 2.3.2 and 3.0.0). However I don't have a real IE8, just IE9 with IE8 mode enabled. It should emulate IE8 fairly accurately, but who knows.

Could you provide me with a link to a live website where the polyfill breaks?

**Comment by petedmarsh** [comment]
I've got a branch with the change here:

~~https://github.com/petedmarsh/internet-explorer-opacity-polyfill/tree/font-awesome-breaks-it~~

(I deleted my fork, the only change in it is to add the `<link>`s described above).

I'm running IE8 using one of the free VMs microsoft provides for cross-browser testing which are available here:

http://www.modern.ie/en-US/virtualization-tools

Some more detail on my set up:

I'm running the VM (IE8 on XP) in Virtual Box 4.2.16 on Ubuntu 12.04 and I used `SimpleHTTPServer` that's built into python to host the page (`python -m SimpleHTTPServer` in the root of the repo).

This is a screenshot of the the error I get:

![image](https://f.cloud.github.com/assets/1192314/938402/41f45136-00fd-11e3-821a-de177d53cde5.png)

And it does work without font awesome :)

It may well be due to being run in a virtual machine, but I'd need access to an XP machine to check.

**Comment by bladeSk** [comment]
No matter what I do, I can't get it to not work :) http://8.brm.sk/t/clipboard_2013-08-09_16-45-38.png
I'll try it on a XP machine tomorrow.

**Comment by petedmarsh** [comment]
Weird! Do you mind if I delete my fork? My branch with the change will be unavailable online after it's gone.

**Comment by bladeSk** [comment]
Go ahead.

**Comment by bladeSk** [comment]
Turns out the problem was that IE6-7 doesn't allow cross-domain reading of stylesheets. That should be fixed now. Inaccessible stylesheets are simply skipped.

**Comment by petedmarsh** [comment]
I just verified that fixes it, thanks!
